//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp.Toolkit.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Erp.Toolkit.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Custom Column 的本地化字符串。
        /// </summary>
        internal static string AddCustomColumn {
            get {
                return ResourceManager.GetString("AddCustomColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After 的本地化字符串。
        /// </summary>
        internal static string After {
            get {
                return ResourceManager.GetString("After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aggregation Expression 的本地化字符串。
        /// </summary>
        internal static string AggregationExpression {
            get {
                return ResourceManager.GetString("AggregationExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alignment Style 的本地化字符串。
        /// </summary>
        internal static string AlignmentStyle {
            get {
                return ResourceManager.GetString("AlignmentStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow Style Overlap 的本地化字符串。
        /// </summary>
        internal static string AllowStyleOverlap {
            get {
                return ResourceManager.GetString("AllowStyleOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And 的本地化字符串。
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Any Part of Field 的本地化字符串。
        /// </summary>
        internal static string AnyPartOfField {
            get {
                return ResourceManager.GetString("AnyPartOfField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply to Entire Row 的本地化字符串。
        /// </summary>
        internal static string ApplyToEntireRow {
            get {
                return ResourceManager.GetString("ApplyToEntireRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ascending 的本地化字符串。
        /// </summary>
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Average 的本地化字符串。
        /// </summary>
        internal static string Avg {
            get {
                return ResourceManager.GetString("Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Before 的本地化字符串。
        /// </summary>
        internal static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Between 的本地化字符串。
        /// </summary>
        internal static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blue Theme 的本地化字符串。
        /// </summary>
        internal static string BlueTheme {
            get {
                return ResourceManager.GetString("BlueTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel All Filters 的本地化字符串。
        /// </summary>
        internal static string CancelAllFilters {
            get {
                return ResourceManager.GetString("CancelAllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Filter 的本地化字符串。
        /// </summary>
        internal static string CancelFilter {
            get {
                return ResourceManager.GetString("CancelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Case Sensitive 的本地化字符串。
        /// </summary>
        internal static string CaseSensitive {
            get {
                return ResourceManager.GetString("CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Category Field 的本地化字符串。
        /// </summary>
        internal static string CategoryField {
            get {
                return ResourceManager.GetString("CategoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Current Value 的本地化字符串。
        /// </summary>
        internal static string CheckCurrentValue {
            get {
                return ResourceManager.GetString("CheckCurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coefficient of Variation 的本地化字符串。
        /// </summary>
        internal static string CoefficientOfVariation {
            get {
                return ResourceManager.GetString("CoefficientOfVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Name 的本地化字符串。
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compare Other Records 的本地化字符串。
        /// </summary>
        internal static string CompareOtherRecords {
            get {
                return ResourceManager.GetString("CompareOtherRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conditional Formatting 的本地化字符串。
        /// </summary>
        internal static string ConditionalFormat {
            get {
                return ResourceManager.GetString("ConditionalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conditional Style Manager 的本地化字符串。
        /// </summary>
        internal static string ConditionalStyleManager {
            get {
                return ResourceManager.GetString("ConditionalStyleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contains 的本地化字符串。
        /// </summary>
        internal static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content cannot be empty! 的本地化字符串。
        /// </summary>
        internal static string ContentCannotBeEmpty {
            get {
                return ResourceManager.GetString("ContentCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count 的本地化字符串。
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Field 的本地化字符串。
        /// </summary>
        internal static string CurrentField {
            get {
                return ResourceManager.GetString("CurrentField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Position 的本地化字符串。
        /// </summary>
        internal static string CurrentPosition {
            get {
                return ResourceManager.GetString("CurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Aggregation Expression 的本地化字符串。
        /// </summary>
        internal static string CustomAggregation {
            get {
                return ResourceManager.GetString("CustomAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Theme 的本地化字符串。
        /// </summary>
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Statistics (Aggregation Manager) 的本地化字符串。
        /// </summary>
        internal static string DataStatistics {
            get {
                return ResourceManager.GetString("DataStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date Filter 的本地化字符串。
        /// </summary>
        internal static string DateFilter {
            get {
                return ResourceManager.GetString("DateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dependent Record Column 的本地化字符串。
        /// </summary>
        internal static string DependentRecordColumn {
            get {
                return ResourceManager.GetString("DependentRecordColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Descending 的本地化字符串。
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display 的本地化字符串。
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Name 的本地化字符串。
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Distinct Count 的本地化字符串。
        /// </summary>
        internal static string DistinctCount {
            get {
                return ResourceManager.GetString("DistinctCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Does Not Contain 的本地化字符串。
        /// </summary>
        internal static string DoesNotContain {
            get {
                return ResourceManager.GetString("DoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Does Not End With 的本地化字符串。
        /// </summary>
        internal static string DoesNotEndWith {
            get {
                return ResourceManager.GetString("DoesNotEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Does Not Start With 的本地化字符串。
        /// </summary>
        internal static string DoesNotStartWith {
            get {
                return ResourceManager.GetString("DoesNotStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Down 的本地化字符串。
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End of Field 的本地化字符串。
        /// </summary>
        internal static string EndOfField {
            get {
                return ResourceManager.GetString("EndOfField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ends With 的本地化字符串。
        /// </summary>
        internal static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entire Field 的本地化字符串。
        /// </summary>
        internal static string EntireField {
            get {
                return ResourceManager.GetString("EntireField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equal 的本地化字符串。
        /// </summary>
        internal static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression Description 的本地化字符串。
        /// </summary>
        internal static string ExpressionDescription {
            get {
                return ResourceManager.GetString("ExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field 的本地化字符串。
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field Properties 的本地化字符串。
        /// </summary>
        internal static string FieldProperties {
            get {
                return ResourceManager.GetString("FieldProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field Property Manager 的本地化字符串。
        /// </summary>
        internal static string FieldPropertyManager {
            get {
                return ResourceManager.GetString("FieldPropertyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field Value 的本地化字符串。
        /// </summary>
        internal static string FieldValue {
            get {
                return ResourceManager.GetString("FieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field Width 的本地化字符串。
        /// </summary>
        internal static string FieldWidth {
            get {
                return ResourceManager.GetString("FieldWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter Content 的本地化字符串。
        /// </summary>
        internal static string FilterContent {
            get {
                return ResourceManager.GetString("FilterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter content cannot be empty! 的本地化字符串。
        /// </summary>
        internal static string FilterContentCannotBeEmpty {
            get {
                return ResourceManager.GetString("FilterContentCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter Direction 的本地化字符串。
        /// </summary>
        internal static string FilterDirection {
            get {
                return ResourceManager.GetString("FilterDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter Expression 的本地化字符串。
        /// </summary>
        internal static string FilterExpression {
            get {
                return ResourceManager.GetString("FilterExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter Scope 的本地化字符串。
        /// </summary>
        internal static string FilterScope {
            get {
                return ResourceManager.GetString("FilterScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find 的本地化字符串。
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find and Filter 的本地化字符串。
        /// </summary>
        internal static string FindAndFilter {
            get {
                return ResourceManager.GetString("FindAndFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find Next 的本地化字符串。
        /// </summary>
        internal static string FindNext {
            get {
                return ResourceManager.GetString("FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find What 的本地化字符串。
        /// </summary>
        internal static string FindWhat {
            get {
                return ResourceManager.GetString("FindWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit Window Size 的本地化字符串。
        /// </summary>
        internal static string FitWindowSize {
            get {
                return ResourceManager.GetString("FitWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format Cells Meeting Criteria 的本地化字符串。
        /// </summary>
        internal static string FormatCellsMeetingCriteria {
            get {
                return ResourceManager.GetString("FormatCellsMeetingCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format Preview 的本地化字符串。
        /// </summary>
        internal static string FormatPreview {
            get {
                return ResourceManager.GetString("FormatPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Four Pages 的本地化字符串。
        /// </summary>
        internal static string FourPages {
            get {
                return ResourceManager.GetString("FourPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Freeze Field 的本地化字符串。
        /// </summary>
        internal static string FreezeField {
            get {
                return ResourceManager.GetString("FreezeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 French 的本地化字符串。
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fuzzy Search by First Letter 的本地化字符串。
        /// </summary>
        internal static string FuzzySearchByFirstLetter {
            get {
                return ResourceManager.GetString("FuzzySearchByFirstLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Geometric Mean 的本地化字符串。
        /// </summary>
        internal static string GeometricMean {
            get {
                return ResourceManager.GetString("GeometricMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 German 的本地化字符串。
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global Search 的本地化字符串。
        /// </summary>
        internal static string GlobalSearch {
            get {
                return ResourceManager.GetString("GlobalSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to First Record 的本地化字符串。
        /// </summary>
        internal static string GoToFirstRecord {
            get {
                return ResourceManager.GetString("GoToFirstRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to Last Record 的本地化字符串。
        /// </summary>
        internal static string GoToLastRecord {
            get {
                return ResourceManager.GetString("GoToLastRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to Next Record 的本地化字符串。
        /// </summary>
        internal static string GoToNextRecord {
            get {
                return ResourceManager.GetString("GoToNextRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to Previous Record 的本地化字符串。
        /// </summary>
        internal static string GoToPreviousRecord {
            get {
                return ResourceManager.GetString("GoToPreviousRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Greater Than 的本地化字符串。
        /// </summary>
        internal static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Greater Than or Equal 的本地化字符串。
        /// </summary>
        internal static string GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("GreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Green Theme 的本地化字符串。
        /// </summary>
        internal static string GreenTheme {
            get {
                return ResourceManager.GetString("GreenTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Harmonic Mean 的本地化字符串。
        /// </summary>
        internal static string HarmonicMean {
            get {
                return ResourceManager.GetString("HarmonicMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Field 的本地化字符串。
        /// </summary>
        internal static string HideField {
            get {
                return ResourceManager.GetString("HideField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information Incomplete 的本地化字符串。
        /// </summary>
        internal static string InfoIncomplete {
            get {
                return ResourceManager.GetString("InfoIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter content to start search 的本地化字符串。
        /// </summary>
        internal static string InputTips {
            get {
                return ResourceManager.GetString("InputTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input value is not a number! 的本地化字符串。
        /// </summary>
        internal static string InputValueNotNumber {
            get {
                return ResourceManager.GetString("InputValueNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid percentile value 的本地化字符串。
        /// </summary>
        internal static string InvalidPercentileValue {
            get {
                return ResourceManager.GetString("InvalidPercentileValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese 的本地化字符串。
        /// </summary>
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kurtosis 的本地化字符串。
        /// </summary>
        internal static string Kurtosis {
            get {
                return ResourceManager.GetString("Kurtosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Landscape 的本地化字符串。
        /// </summary>
        internal static string Landscape {
            get {
                return ResourceManager.GetString("Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Month 的本地化字符串。
        /// </summary>
        internal static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Quarter 的本地化字符串。
        /// </summary>
        internal static string LastQuarter {
            get {
                return ResourceManager.GetString("LastQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Week 的本地化字符串。
        /// </summary>
        internal static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Year 的本地化字符串。
        /// </summary>
        internal static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Less Than 的本地化字符串。
        /// </summary>
        internal static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Less Than or Equal 的本地化字符串。
        /// </summary>
        internal static string LessThanOrEqual {
            get {
                return ResourceManager.GetString("LessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Theme 的本地化字符串。
        /// </summary>
        internal static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manager 的本地化字符串。
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match Mode 的本地化字符串。
        /// </summary>
        internal static string MatchMode {
            get {
                return ResourceManager.GetString("MatchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum 的本地化字符串。
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Median 的本地化字符串。
        /// </summary>
        internal static string Median {
            get {
                return ResourceManager.GetString("Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Meet Any Condition 的本地化字符串。
        /// </summary>
        internal static string MeetAnyCondition {
            get {
                return ResourceManager.GetString("MeetAnyCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu Name 的本地化字符串。
        /// </summary>
        internal static string MenuName {
            get {
                return ResourceManager.GetString("MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu name content cannot be empty! 的本地化字符串。
        /// </summary>
        internal static string MenuNameContentCannotBeEmpty {
            get {
                return ResourceManager.GetString("MenuNameContentCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum 的本地化字符串。
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mode 的本地化字符串。
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Down 的本地化字符串。
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Up 的本地化字符串。
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Aggregation Expression 的本地化字符串。
        /// </summary>
        internal static string NewAggregationExpression {
            get {
                return ResourceManager.GetString("NewAggregationExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Format Rule 的本地化字符串。
        /// </summary>
        internal static string NewFormatRule {
            get {
                return ResourceManager.GetString("NewFormatRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Month 的本地化字符串。
        /// </summary>
        internal static string NextMonth {
            get {
                return ResourceManager.GetString("NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Page 的本地化字符串。
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Quarter 的本地化字符串。
        /// </summary>
        internal static string NextQuarter {
            get {
                return ResourceManager.GetString("NextQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Week 的本地化字符串。
        /// </summary>
        internal static string NextWeek {
            get {
                return ResourceManager.GetString("NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Year 的本地化字符串。
        /// </summary>
        internal static string NextYear {
            get {
                return ResourceManager.GetString("NextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Between 的本地化字符串。
        /// </summary>
        internal static string NotBetween {
            get {
                return ResourceManager.GetString("NotBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Equal 的本地化字符串。
        /// </summary>
        internal static string NotEqual {
            get {
                return ResourceManager.GetString("NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number Filter 的本地化字符串。
        /// </summary>
        internal static string NumberFilter {
            get {
                return ResourceManager.GetString("NumberFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation Failed 的本地化字符串。
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orange Theme 的本地化字符串。
        /// </summary>
        internal static string OrangeTheme {
            get {
                return ResourceManager.GetString("OrangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page Number 的本地化字符串。
        /// </summary>
        internal static string PageNumber {
            get {
                return ResourceManager.GetString("PageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page Setup 的本地化字符串。
        /// </summary>
        internal static string PageSetup {
            get {
                return ResourceManager.GetString("PageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter 的本地化字符串。
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Percentile 的本地化字符串。
        /// </summary>
        internal static string Percentile {
            get {
                return ResourceManager.GetString("Percentile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Percentile (0-100) 的本地化字符串。
        /// </summary>
        internal static string PercentileValueRange {
            get {
                return ResourceManager.GetString("PercentileValueRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Percentile value must be between 0 and 100 的本地化字符串。
        /// </summary>
        internal static string PercentileValueRangeError {
            get {
                return ResourceManager.GetString("PercentileValueRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Period 的本地化字符串。
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please add at least one aggregation expression! 的本地化字符串。
        /// </summary>
        internal static string PleaseAddAtLeastOneAggregationExpression {
            get {
                return ResourceManager.GetString("PleaseAddAtLeastOneAggregationExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select at least one field to be categorized! 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectAtLeastOneCategoryField {
            get {
                return ResourceManager.GetString("PleaseSelectAtLeastOneCategoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select to set field renaming! 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectRenameField {
            get {
                return ResourceManager.GetString("PleaseSelectRenameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the field to be counted! 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectStatisticalField {
            get {
                return ResourceManager.GetString("PleaseSelectStatisticalField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Population Standard Deviation 的本地化字符串。
        /// </summary>
        internal static string PopulationStandardDeviation {
            get {
                return ResourceManager.GetString("PopulationStandardDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Population Variance 的本地化字符串。
        /// </summary>
        internal static string PopulationVariance {
            get {
                return ResourceManager.GetString("PopulationVariance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Portrait 的本地化字符串。
        /// </summary>
        internal static string Portrait {
            get {
                return ResourceManager.GetString("Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Position Index 的本地化字符串。
        /// </summary>
        internal static string PositionIndex {
            get {
                return ResourceManager.GetString("PositionIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Page 的本地化字符串。
        /// </summary>
        internal static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print Preview 的本地化字符串。
        /// </summary>
        internal static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print time 的本地化字符串。
        /// </summary>
        internal static string PrintTime {
            get {
                return ResourceManager.GetString("PrintTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print Width 的本地化字符串。
        /// </summary>
        internal static string PrintWidth {
            get {
                return ResourceManager.GetString("PrintWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product 的本地化字符串。
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties 的本地化字符串。
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purple Theme 的本地化字符串。
        /// </summary>
        internal static string PurpleTheme {
            get {
                return ResourceManager.GetString("PurpleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quartile 的本地化字符串。
        /// </summary>
        internal static string Quartile {
            get {
                return ResourceManager.GetString("Quartile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quartile (1-3) 的本地化字符串。
        /// </summary>
        internal static string QuartileValueRange {
            get {
                return ResourceManager.GetString("QuartileValueRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range 的本地化字符串。
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read Only 的本地化字符串。
        /// </summary>
        internal static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename 的本地化字符串。
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore Last Filter 的本地化字符串。
        /// </summary>
        internal static string RestoreLastFilter {
            get {
                return ResourceManager.GetString("RestoreLastFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root Mean Square 的本地化字符串。
        /// </summary>
        internal static string RootMeanSquare {
            get {
                return ResourceManager.GetString("RootMeanSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rule Applies to This Column 的本地化字符串。
        /// </summary>
        internal static string RuleAppliesToColumn {
            get {
                return ResourceManager.GetString("RuleAppliesToColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rule Format 的本地化字符串。
        /// </summary>
        internal static string RuleFormat {
            get {
                return ResourceManager.GetString("RuleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rules (Applied in Order) 的本地化字符串。
        /// </summary>
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search by Format 的本地化字符串。
        /// </summary>
        internal static string SearchByFormat {
            get {
                return ResourceManager.GetString("SearchByFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search content cannot be empty! 的本地化字符串。
        /// </summary>
        internal static string SearchContentCannotBeEmpty {
            get {
                return ResourceManager.GetString("SearchContentCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Direction 的本地化字符串。
        /// </summary>
        internal static string SearchDirection {
            get {
                return ResourceManager.GetString("SearchDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Scope 的本地化字符串。
        /// </summary>
        internal static string SearchScope {
            get {
                return ResourceManager.GetString("SearchScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected 的本地化字符串。
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Rule Type 的本地化字符串。
        /// </summary>
        internal static string SelectRuleType {
            get {
                return ResourceManager.GetString("SelectRuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simplified Chinese 的本地化字符串。
        /// </summary>
        internal static string SimplifiedChinese {
            get {
                return ResourceManager.GetString("SimplifiedChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single Page 的本地化字符串。
        /// </summary>
        internal static string SinglePage {
            get {
                return ResourceManager.GetString("SinglePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Six Pages 的本地化字符串。
        /// </summary>
        internal static string SixPages {
            get {
                return ResourceManager.GetString("SixPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skewness 的本地化字符串。
        /// </summary>
        internal static string Skewness {
            get {
                return ResourceManager.GetString("Skewness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort Order 的本地化字符串。
        /// </summary>
        internal static string SortOrder {
            get {
                return ResourceManager.GetString("SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort Type 的本地化字符串。
        /// </summary>
        internal static string SortType {
            get {
                return ResourceManager.GetString("SortType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard Deviation 的本地化字符串。
        /// </summary>
        internal static string StandardDeviation {
            get {
                return ResourceManager.GetString("StandardDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start of Field 的本地化字符串。
        /// </summary>
        internal static string StartOfField {
            get {
                return ResourceManager.GetString("StartOfField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starts With 的本地化字符串。
        /// </summary>
        internal static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statistical Indicator 的本地化字符串。
        /// </summary>
        internal static string StatisticalIndicator {
            get {
                return ResourceManager.GetString("StatisticalIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statistic Field 的本地化字符串。
        /// </summary>
        internal static string StatisticField {
            get {
                return ResourceManager.GetString("StatisticField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statistics 的本地化字符串。
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sum 的本地化字符串。
        /// </summary>
        internal static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sum Absolute 的本地化字符串。
        /// </summary>
        internal static string SumAbsolute {
            get {
                return ResourceManager.GetString("SumAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sum Product 的本地化字符串。
        /// </summary>
        internal static string SumProduct {
            get {
                return ResourceManager.GetString("SumProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sum of Squares 的本地化字符串。
        /// </summary>
        internal static string SumSquares {
            get {
                return ResourceManager.GetString("SumSquares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Printer 的本地化字符串。
        /// </summary>
        internal static string SwitchPrinter {
            get {
                return ResourceManager.GetString("SwitchPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Style 的本地化字符串。
        /// </summary>
        internal static string SystemStyle {
            get {
                return ResourceManager.GetString("SystemStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Filter 的本地化字符串。
        /// </summary>
        internal static string TextFilter {
            get {
                return ResourceManager.GetString("TextFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Month 的本地化字符串。
        /// </summary>
        internal static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Quarter 的本地化字符串。
        /// </summary>
        internal static string ThisQuarter {
            get {
                return ResourceManager.GetString("ThisQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Week 的本地化字符串。
        /// </summary>
        internal static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Year 的本地化字符串。
        /// </summary>
        internal static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tomorrow 的本地化字符串。
        /// </summary>
        internal static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Number of Items 的本地化字符串。
        /// </summary>
        internal static string TotalItemCount {
            get {
                return ResourceManager.GetString("TotalItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traditional Chinese 的本地化字符串。
        /// </summary>
        internal static string TraditionalChinese {
            get {
                return ResourceManager.GetString("TraditionalChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two Pages 的本地化字符串。
        /// </summary>
        internal static string TwoPages {
            get {
                return ResourceManager.GetString("TwoPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unfreeze All Fields 的本地化字符串。
        /// </summary>
        internal static string UnfreezeAllFields {
            get {
                return ResourceManager.GetString("UnfreezeAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhide Field 的本地化字符串。
        /// </summary>
        internal static string UnhideField {
            get {
                return ResourceManager.GetString("UnhideField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown type parameter 的本地化字符串。
        /// </summary>
        internal static string UnknownTypeParameter {
            get {
                return ResourceManager.GetString("UnknownTypeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Up 的本地化字符串。
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variance 的本地化字符串。
        /// </summary>
        internal static string Variance {
            get {
                return ResourceManager.GetString("Variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 的本地化字符串。
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width Mode 的本地化字符串。
        /// </summary>
        internal static string WidthMode {
            get {
                return ResourceManager.GetString("WidthMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Year To Date 的本地化字符串。
        /// </summary>
        internal static string YearToDate {
            get {
                return ResourceManager.GetString("YearToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yesterday 的本地化字符串。
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom Level 的本地化字符串。
        /// </summary>
        internal static string ZoomLevel {
            get {
                return ResourceManager.GetString("ZoomLevel", resourceCulture);
            }
        }
    }
}
